/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LowPolyDino.glb 
*/

import { useGLTF } from '@react-three/drei'
import LowPolyDino from '../assets/glb/LowPolyDino.glb'

export default function Model(props) {
  const { nodes, materials } = useGLTF(LowPolyDino)
  return (
    <group {...props} dispose={null} scale={30} position={[90,-10,10]} rotation={[0, 3, 0]}>
      <primitive object={nodes.Bone} />
      <primitive object={nodes.Bone001} />
      <group position={[-0.142, 0.032, 0.06]} scale={[0.609, 0.609, 1.042]}>
        <skinnedMesh geometry={nodes.Cube001.geometry} material={materials.Dino} skeleton={nodes.Cube001.skeleton} />
        <skinnedMesh geometry={nodes.Cube001_1.geometry} material={materials.Dino2} skeleton={nodes.Cube001_1.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload(LowPolyDino)
